apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: CP Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA1
          artifact-id: af9164d5-1d3d-4d49-9c53-f4c7ffc15dee
          target-environment: QA-env
    